---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/TheCognizantFoundry/Collabs-UI.git
    branch: master
    username: deyvasigamani
    password: vasansund@3

- name: deploy-to-pcf
  type: cf-cli-resource
  source:
    api: https://api.sys.dev.cloudsprint.io
    username: Deyvasigamani.sundaramurthy@cognizant.com
    password: Vasansund@piv3
    org: colabs
    space: dev 
    skip_cert_check: true
    


jobs:
- name: build_and_verify
  plan:
  - get: source-code
    trigger: true
  - task: build-artifact
    file: source-code/ci/tasks/build.yml
    input_mapping: {source-code: source-code}
  - put: deploy-to-pcf
    params:
      command: zero-downtime-push
      manifest: uiCode/manifest.yml


            
  
